version: '3'
services:
  api: 
    build: .
    image: 'api'
    env_file: .env
    ports:
      - '3000:3000'
    container_name: 'api'
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongo
      - redis

  redis:
    container_name: flexredis
    restart: always
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes: 
      - ./redis/data:/data

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_NON_ROOT_USERNAME: ${MONGO_NON_ROOT_USERNAME}
      MONGO_NON_ROOT_PASSWORD: ${MONGO_NON_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./scripts/mongo/mongo-user-entrypoint.sh:/docker-entrypoint-initdb.d/mongo-user-entrypoint.sh
      - ./mongodb/data:/data/db
      - ./mongodb/mongodb_config:/data/configdb